### ISSUE TITLE
Error during "Getting Started"

### ISSUE THREAD

**Issue by cloudlena** [push2cloud/push2cloud#1]
- **Version**: CLI 1.0.2
- **Platform**: Darwin Kernel Version 15.5.0
- **Module**: deployer example

Trying to run the step `p2c compile -e ../manifests/deployment.json` of the Getting Started tutorial throws the error `Cannot find module 'push2cloud-compiler-git-no-archive'`.

**Comment by adrai** [comment]
Which node version are you using?

**Comment by adrai** [comment]
node 6.x?

**Comment by cloudlena** [comment]
node 6.2.0
npm 3.9.3

**Comment by adrai** [comment]
the problem is npm... we did not test the globally installed cli with npm 3.x right now...
as a workaround you can try this: `./node_modules/.bin/p2c compile -e ../manifests/deployment.json`

**Comment by adrai** [comment]
ok... immediately fixed... should work with push2cloud-cli v1.0.3 ;-)

**Comment by cloudlena** [comment]
Yup, that fixed it. Thanks for the quick fix, @adrai!
